// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHdjnT1_7CSStumncnm4ffF3MNSsOJdF4',
    appId: '1:168263074411:web:375828a9da1dada9f5a72e',
    messagingSenderId: '168263074411',
    projectId: 'i-crash-pt-2026',
    authDomain: 'i-crash-pt-2026.firebaseapp.com',
    storageBucket: 'i-crash-pt-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUwqt6kOUNyxEQscTZzC7Xfk4n6279IsE',
    appId: '1:168263074411:android:89d93dc2a6161f4bf5a72e',
    messagingSenderId: '168263074411',
    projectId: 'i-crash-pt-2026',
    storageBucket: 'i-crash-pt-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlZb0DMFKI3wvv1qexUa12e4nsvnWFD4',
    appId: '1:168263074411:ios:fad2efdbcf8ab929f5a72e',
    messagingSenderId: '168263074411',
    projectId: 'i-crash-pt-2026',
    storageBucket: 'i-crash-pt-2026.firebasestorage.app',
    iosBundleId: 'pt.icrash.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAlZb0DMFKI3wvv1qexUa12e4nsvnWFD4',
    appId: '1:168263074411:ios:64cd757a89a58580f5a72e',
    messagingSenderId: '168263074411',
    projectId: 'i-crash-pt-2026',
    storageBucket: 'i-crash-pt-2026.firebasestorage.app',
    iosBundleId: 'pt.icrash.app.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHdjnT1_7CSStumncnm4ffF3MNSsOJdF4',
    appId: '1:168263074411:web:626e86f06a77a0d0f5a72e',
    messagingSenderId: '168263074411',
    projectId: 'i-crash-pt-2026',
    authDomain: 'i-crash-pt-2026.firebaseapp.com',
    storageBucket: 'i-crash-pt-2026.firebasestorage.app',
  );
}
